### ISSUE TITLE
Built-in functions?

### ISSUE THREAD

**Issue by ronaldtse** [riboseinc/nereon-syntax#6]
Terraform provides a number of built-in interpolation functions here:
https://www.terraform.io/docs/configuration/interpolation.html

Do we need any built-in interpolation functions, or can we go the modular way (as in Rust)?

**Comment by drystone** [comment]
Built-in is going to be the most straightforward. We can think about embedding a scripting language, perhaps Lua or Python, in the future but initially we can write a simple expression evaluator with support for a defined set of functions (such as those used by Terraform).

**Comment by ronaldtse** [comment]
I agree that we can go built-in for now, we could also have those separately defined in modules. 

One failure in Terraform scripting is the lack of types and objects, where everything falls back to being a String (a JSON string). We should have types and their properties/functions defined early on so the program/script functions as expected, with less reliance on trial and error.

**Comment by drystone** [comment]
Using anything other than strings in the config/config parser adds unnecessary complexity. These values are reinterpreted by the program once the config is loaded anyway. I daresay that's why Terraform decided to stick with strings. As did Unix (environment variables and program arguments) and XML, HTML ...

It would be the job of the NOS to ensure these string values can be parsed into the specific types required by the program itself.

Interpolation functions names can indicate the type of data expected (ie . `add` for numbers, `concat` for strings)

**Comment by ronaldtse** [comment]
XML supports all sorts of data types. JSON also supports numbers, booleans, arrays, objects and null.

I think what I'm against is "processing" everything as a string. For example, Terraform supports numerical calculation, but you have to disguise it as a string to do it, e.g., `"${100 + 200}"` and returns `"300"`. To me, that is wrong, it should have been just `100 + 200` and returning `300`.

For example,
```hcl
config "example" {
  port = 8000 + (instanceNum * 10)
}
```

Is superior than Terraform's syntax:

```hcl
config "example" {
  port = "${8000 + "${var.instanceNum * 10}"}"
}
```

**Comment by drystone** [comment]
> XML supports all sorts of data types. JSON also supports numbers, booleans, arrays, objects and null.

Semantically, yes, I agree but unlike JSON, syntactically XML has no concept of number.

And yes, the Terraform syntax is awkward. I see what you meant by "trial and error" now!

I think we could get something closer to your example, specifically binary operators could easily be supported because there's no ambiguity (left is an lvalue, right is an rvalue). Unary operators pose more of a problem for parsers but I guess we can define functions for them - `negate()`, `not()` etc.
```
config "example" {
  port = 8000 + (instanceNum * 10)
}
```
is ambiguous: `config` is a string (key) but `instanceNum` is an interpolated value.
I'd prefer to see:
```
config "example" {
  port = 8000 + (${instanceNum} * 10)
}
```
because, by not having to quote strings, it would permit:
```
config example {
  port = 8000 + (${instanceNum} * 10)
}
```
and I think it's better not to worry about quoting strings :)

eg.
```
config example {
    host = "loaclahost"
}
```
```
"config" "example" {
    host localhost
}
```
```
config example host localhost
```
can be equivalent.

**Comment by ronaldtse** [comment]
It would be awesome if we can separate strings and variables, where strings are quoted but variables not.

For example, in:
```
config "example" {
  port = 8000 + (instanceNum * 10)
}
```

`config`, `port` and `instanceNum` already stand out being unquoted strings, and they are most certainly not supposed to be strings. In symbol resolution we can easily differentiate which ones are keywords, or if it's too tough to parse, we could always use `$instanceNum`. Personally I prefer `instanceNum` over `${instanceNum}`.

**Comment by drystone** [comment]
Aren't
```
config "example" {
  port = 8000 + (instanceNum * 10)
}
```
and
```
config {
    example {
        port = 8000 + (instanceNum * 10)
    }
}
```
supposed to be equivalent? In which case `example` should/shouldn't be quoted?

Also (and I appreciate you use the term loosely) there is no concept of variables in that they can't change. `instanceNum` can only be a value. However, to implement this we could have a `repeat()` function - something like:

```
looped_node {
    port = 1000 + (count() * 10)
}
config "example" {
    repeat(${node:looped_node}, 4)
}
```
which would resolve to something like:
```
looped_node {
    port = 1000 + (count() * 10)
}
config "example" {
    port "0" = 1000
    port "1" = 1010
    port "2" = 1020
    port "3" = 1030
}
```

**Comment by ronaldtse** [comment]
I wonder if we should lose the UCL-ness of the syntax, this doesn't look very clear:

```
config {
    example {
        port = 8000 + (instanceNum * 10)
    }
}
```

(i.e., `config` is like a object/function name, `example` is a variable name, `port` is an attribute, `instanceNum` is a variable name)

And when you brought up looping, isn't having a real iterator better? (Ruby-ish, somewhat Rust-y).

```
for i in 0..4 {
  config "example_#{i}" {
    port = 1000 + (i * 10)
  }
}
```

**Comment by drystone** [comment]
Yes, in that case. What about this:
```
config {
    example {
        port = 8000 + (instanceNum * 10)
        host = localhost
        timeout = 25
    }
}
```
which could be:
```
config example port = 8000 + (instanceNum * 10)
config example host = localhost
config example timeout = 25
```
or
```
config {
    example port = 8000 + (instanceNum * 10)
    example host = localhost
    example timeout = 25
}
```
or anything in between!?

Incidentally, where is `instanceNum` coming from?

Seems this is emerging as a scripting language - or templating hybrid. PHP springs to mind. Which is a tangled mix of data and code IMHO. In the `for` example there are at least 2 overloaded meanings of `{`: code/variable and dictionary delimiter.

I can see the appeal of being able to generate configs on-the-fly but I wonder whether we'd be better defining a syntax for static configuration and developing a different tool (or using an existing one such as `sed`) to mutate config files.

Perhaps we should consider a third format, maybe NOT ... Nereon Object Templates. Which is unashamedly a templating language that can be used as the basis for NOC and NOS. Something like [mustache](https://mustache.github.io/mustache.5.html)?

What appeals to me about the strings and functions approach is conceptually it's really simple. Config is a tree with strings as leaf nodes. A leaf node can be replaced by a function, say `date()` and it's explicitly clear what is going to happen. Then it's not too much of a stretch for users to grok `union()` which takes two nodes and combines them into a single dictionary. Similarly `repeat()` which populates a dictionary with key / node pairs. The syntax is relatively clean and the parser only needs to differentiate between functions, values and arithmetic operators. The logic for the functions gets moved into the interpolation phase rather than having to be parsed.

The downside of the `repeat` described above is that the `looped_node` remains in the config as cruft. Which is why templates may be a preferable solution. Or maybe a convention whereby certain nodes are culled after interpolation.

**Comment by ronaldtse** [comment]
Sorry for the delay in replying. You are right we need to define two things:

* an static / fully-realized NOC (i.e. no interpolations or code present); vs
* a dynamic / programmable NOC.

I'm assuming that you're calling the static NOC the "NOC", and the dynamic one the "NOT". Maybe "NOD" (D for dynamic) or "NOP" (P for programmable, and sounds like no-op) would be better since a "template" is often considered something static itself.

The templating concept gets eerily close to what we are doing with [Selagraph](https://github.com/riboseinc/selagraph/blob/master/rice.sel), a text markup language that supports programming features.

The nature about "templating renderers" like mustache is that they are purely textual functions that do not consider the semantics and context of the underlying code (the thing it is templating for). Very often you need to manually separate the logic and duplicate it.

The "dynamic" part is to allow something like this:

```
config "hello" {
  id = 12
}
# or config hello id 12 # maybe the last argument is implicitly a value?
# or config.hello.id = 12

for i in 0..4 {
  config "example_#{i}" {
    port = 1000 + (config.hello.id * 10)
  }
}
```

Notice that the phrase `port = 1000 + (config.hello.id * 10)` cannot be done in a normal templating renderer like mustache, because the renderer will not have access to the `config.hello` context. Various tweaks has to be done to make this work for usual template renderers.

The challenge for the NOT/NOD/NOP is to blend this well.

P.S. I think your mention of this is ideal:

```
config {
    example {
        port = 8000 + (instanceNum * 10)
        host = localhost
        timeout = 25
    }
}

# is equivalent to

config example port = 8000 + (instanceNum * 10)
config example host = localhost
config example timeout = 25

# is equivalent to

config {
    example port = 8000 + (instanceNum * 10)
    example host = localhost
    example timeout = 25
}
```


If we can assume the last argument is always a value, this also works:
```
config example port (8000 + (instanceNum * 10))
config example host localhost
config example timeout 25
```

And this is really similar to how the Cisco IOS CLI and JunOS CLI works, which is very nice:
* JunOS CLI guide: https://www.juniper.net/documentation/en_US/junos/information-products/pathway-pages/junos-cli/junos-cli.pdf

**Comment by drystone** [comment]
```
config example port (8000 + (instanceNum * 10))
config example host localhost
config example timeout 25
```
Agreed, very nice :-)

Although we potentially could also dispense with the curly brace syntax, it is worth keeping as a handy shorthand for stanzas to logically group items.

Any string can optionally be quoted so, for example, we could use
```
"config-server" example host localhost
```
to allow non-alphanum in key names.

Keeping NOC entirely static is a good aim but this shouldn't preclude expansions that will always expand to the same value. In which case `date()` and `env()` are out (although environment variables can still be injected via NOS at runtime). `include()` can be used to include external files (maybe supporting URLs too, and globbing to include multiple files). `copy()` can duplicate an existing node as a rudimentary template syntax.

I'm still concerned about template nodes appearing in the parsed config. Perhaps any key beginning with `_` could be dropped from the final result: 

```
_template {
    port 8000 + arg(1) * 10
    host localhost
    timeout 25
}

config example1 copy(_template 0)
config example2 copy(_template 1)
```
will parse to:
```
config {
    example1 {
        port 8000
        host localhost
        timeout 25
    }
    example2 {
        port 8010
        host localhost
        timeout 25
    }
}
```

**Arrays**: these are essentially dictionaries keyed with numbers. Would a `list` shorthand be sufficient? Something like:
```
_template {
    port 8000 + arg(1) * 10
    host localhost
    timeout 25
}

config list(copy(_template 0) copy(_template 1))
```
which will parse to:
```
config {
    0 {
        port 8000
        host localhost
        timeout 25
    }
    1 {
        port 8010
        host localhost
        timeout 25
    }
}
```
I appreciate this could require applications to convert from objects to arrays but it shouldn't be too onerous - a nereon library could provide suitable helper functions.

**Comment by ronaldtse** [comment]
> Any string can optionally be quoted so, for example, we could use
> `"config-server" example host localhost`
> to allow non-alphanum in key names.

Agreed.

> Keeping NOC entirely static is a good aim but this shouldn't preclude expansions that will always expand to the same value.

Agreed as well.

> I'm still concerned about template nodes appearing in the parsed config. Perhaps any key beginning > with _ could be dropped from the final result:
> ```
> _template {
>     port 8000 + arg(1) * 10
>     host localhost
>     timeout 25
> }
> 
> config example1 copy(_template 0)
> config example2 copy(_template 1)
> ```

It feels that we're actually defining a template function, which isn't a bad thing itself. But we do want to explicitly separate a variable/template assignment from the usage of it, for example, `_template` here is an assignment. It would be more clear if we do:

```
let my_template = {
    port 8000 + arg(1) * 10
    host localhost
    timeout 25
}

config example1 my_template(0)
config example2 my_template(1)
```

(we also need to know when the defined variable is released/out-of-scope)

For arrays, I've always found the array-as-list syntax confusing, I'd rather have something like this:

```
config {
    [{ // 0
        port 8000
        host localhost
        timeout 25
    },
    { // 1
        port 8010
        host localhost
        timeout 25
    }]
}
```

Do you have some concerns in mind for a more "array-native" syntax like this?

**Comment by drystone** [comment]
> It feels that we're actually defining a template function, which isn't a bad thing itself. But we do want to explicitly separate a variable/template assignment from the usage of it, for example, _template here is an assignment.

Ok, great. I'd rather not use an assignment operator but a macro, something like:
```
define(template {
    port 8000 + arg(1) * 10
    host localhost
    timeout 25
})
```
This does exactly as you suggest but is straightforward to parse, is more explicit than the `_template` I described above and doesn't hint at any sort of 'runability'. Though perhaps the macro would be better named `template` (not `define`).

Scope-wise we need a path syntax. We could use `/` and `..` as per file system or something more explicit such as `root()` and `parent()`. either way we'll need to be careful what  parent refers to.
```
config example {
    port 8000
    host localhost
    timeout 25
    name format("{}:{}", parent() host, root() config example port)
    // or name format("{}:{}", ../host, /config/example/port)
}
```
Do you have a preference?

[EDIT] I suggest something other than `/` for root as we'll probably want that for arithmetic division. Rust uses `::` which could be used in conjunction with `^`:
```
name format("{}:{}", ^::host, ::config::example::port)
```

**Comment by drystone** [comment]
Ah, forgot about arrays ... I was on a mission to keep operators to a minimum but you're quite right, `[]` is preferable to `list()`

**Comment by ronaldtse** [comment]
The `define` syntax works but it really feels like a macro.

Maybe something like this works better?
```
let template ({
    port 8000 + arg(1) * 10
    host localhost
    timeout 25
})
```

What exactly are the scope and paths needed for?

**Comment by drystone** [comment]
I'm hoping we could avoid the use of keywords. Though I'd be happy with:
```
let(template_name, {
    port 8000 + arg(1) * 10
    host localhost
    timeout 25
})
```
After long consideration I think paths are unnecessary. I was thinking along the lines of being able to reference one node from a macro to generate another. The main problem here is order of expansion and being able to guarantee that once a node is used in an expansion it can never get updated/replaced (eg when a node set in a config file is overwritten by a command line argument from the NOS). I've therefore decided against this approach.

Instead, expansions will only work on templates or immediate values. So the `let` syntax is useful:
```
let(logdir, /var/log)
app riffol logfile format("{}/riffol.log", @logdir)
app nereon logfile format("{}/nereon.log", @logdir)
```
Nothing fancy, just a way to reuse chunks of configuration.

A path syntax may be helpful in the NOS to define which nodes parameters are to be injected into but I don't think they need to be a part of NOC syntax.

Scope/namespace. I was considering allowing template names declared within a dictionary node to override a similarly named template in an outer dictionary. Currently I think its complexity outweighs its usefulness. So, for the time being at least, there's a single template namespace and re-declaring a template will replace the original from that point forward.
```
let(name, outer)
name @name
inner {
    let(name, inner)
    name @name
}
name @name
```
resulting in
```
name outer
inner {
    name inner
}
name inner
```
Also, templates are normally only accessible in the file they are declared in. I'm looking at two macros to include content into a NOC. `include(filename)` will include the text from the file verbatim (so templates in the outer file can be used in the included file). This will allow, for example, lists to be held in separate files. Then there's `noc(filename)` which will parse the file as a separate NOC (ie no access to the outer files templates) and use the resulting node as the expansion. value.

**Comment by ronaldtse** [comment]
@drystone sorry for the late reply. I'm not quite convinced that the `x(y)` syntax is easier to parse, because the content will contain closing `)` anyway, meaning that we still need a grammar parser...

Since there are a number of Rust grammar parsers, perhaps it's not hard to have a cleaner language?

**Comment by ronaldtse** [comment]
@drystone should we close this or is there something to follow? Thanks!

**Comment by drystone** [comment]
Happy to close @ronaldtse. To date only a couple of built in functions are implemented. Requests for specific functions should be raised as separate issues.
